steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'gcr.io/$PROJECT_ID/welcome-app:staging', 'app']
    dir: 'Staging'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/welcome-app:staging']
    dir: 'Staging'

  - name: 'hashicorp/terraform:1.5.7'
    args: ['init']
    dir: 'Staging'

  - name: 'hashicorp/terraform:1.5.7'
    args: ['apply', '-auto-approve']
    dir: 'Staging'

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s